import type { Metadata } from "next";
import { Poppins, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import { OrderProvider } from "./providers";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500","600","700","800"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`flex flex-col ${poppins.variable} ${geistMono.variable} antialiased mx-auto w-full h-full`}
      >
        <OrderProvider>
          <div className="w-screen min-w-screen">
            <Header />
          </div>
          <div className="mx-auto w-screen md:h-full md:max-w-[1280px] -mt-[50px]">
            {children}
          </div>
        </OrderProvider>
      </body>
    </html>
  );
}
